### PR TITLE
Optomized low for faster response times.

### PR DESCRIPTION
**Pull request by Phara0h**
Did some optimizations and gained ~15% performance increase in regards to requests per second (throughput). The same functionality just a faster way to do some of the operations it was doing.

### CODE REVIEW

**Comment by jkyberneees** [comment]
Hi @Phara0h, your contribution is indeed highly appreciated. You are right, I can confirm such performance improvements on my side as well.

Thanks

**Comment by Phara0h** [comment]
No problem :D. Thinking about making a new lib with a version of your stuff, some of my QOL code and only the http stuff of uWebSockets all combined into one project. Got some trial code going and managed to get another 10% gain (pushing over 125k rps on my laptop). Maybe we could combine our efforts into this project and smoke the competition out there :D

**Comment by jkyberneees** [comment]
Hi @Phara0h I would be interested in more details of your project. Just let me know when you are ready to share some code. 
Best Regards

**Comment by Phara0h** [comment]
https://github.com/Phara0h/Ouroborus 
Here it is, and its screaming fast. Down to coordinate on discord or whatever.

**Comment by jkyberneees** [comment]
Hi @Phara0h thanks for sharing your initial implementations. 
Can you write me to kyberneees@gmail.com or any other preferred way to exchange some feedback?
Thanks

PS: Is not this sensitive https://github.com/Phara0h/Ouroborus/blob/master/appveyor.yml#L12 ?

**Pull request merged**
